# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.4.0

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Support for programming with names and binders using GHC Generics"
HOMEPAGE="https://github.com/lambdageek/unbound-generics"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"

RDEPEND=">=dev-haskell/ansi-wl-pprint-0.6.7.2:=[profile?] <dev-haskell/ansi-wl-pprint-1.1:=[profile?]
	>=dev-haskell/contravariant-0.5:=[profile?]
	>=dev-haskell/profunctors-4.0:=[profile?]
	>=dev-haskell/transformers-compat-0.3:=[profile?]
	>=dev-lang/ghc-8.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.2.0.0
	test? ( >=dev-haskell/quickcheck-2.7 <dev-haskell/quickcheck-3
		dev-haskell/tasty
		dev-haskell/tasty-hunit
		dev-haskell/tasty-quickcheck )
"
