# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.3

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="CAES Language for Synchronous Hardware"
HOMEPAGE="http://www.clash-lang.org/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/bifunctors-4.1.1:=[profile?] <dev-haskell/bifunctors-5.5:=[profile?]
	>=dev-haskell/clash-lib-0.7.1:=[profile?] <dev-haskell/clash-lib-0.8:=[profile?]
	>=dev-haskell/clash-prelude-0.11.2:=[profile?] <dev-haskell/clash-prelude-0.12:=[profile?]
	>=dev-haskell/clash-systemverilog-0.7.2:=[profile?] <dev-haskell/clash-systemverilog-0.8:=[profile?]
	>=dev-haskell/clash-verilog-0.7.2:=[profile?] <dev-haskell/clash-verilog-0.8:=[profile?]
	>=dev-haskell/clash-vhdl-0.7.2:=[profile?] <dev-haskell/clash-vhdl-0.8:=[profile?]
	>=dev-haskell/ghc-typelits-extra-0.1.3:=[profile?] <dev-haskell/ghc-typelits-extra-0.3:=[profile?]
	>=dev-haskell/ghc-typelits-knownnat-0.1.2:=[profile?] <dev-haskell/ghc-typelits-knownnat-0.4:=[profile?]
	>=dev-haskell/ghc-typelits-natnormalise-0.4.3:=[profile?] <dev-haskell/ghc-typelits-natnormalise-0.6:=[profile?]
	>=dev-haskell/hashable-1.1.2.3:=[profile?] <dev-haskell/hashable-1.3:=[profile?]
	>=dev-haskell/haskeline-0.7.0.3:=[profile?] <dev-haskell/haskeline-0.8:=[profile?]
	>=dev-haskell/lens-4.0.5:=[profile?] <dev-haskell/lens-4.16:=[profile?]
	>=dev-haskell/mtl-2.1.1:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	>=dev-haskell/text-0.11.3.1:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-haskell/unbound-generics-0.1:=[profile?] <dev-haskell/unbound-generics-0.4:=[profile?]
	>=dev-haskell/uniplate-1.6.12:=[profile?] <dev-haskell/uniplate-1.8:=[profile?]
	>=dev-haskell/unordered-containers-0.2.1.0:=[profile?] <dev-haskell/unordered-containers-0.3:=[profile?]
	>=dev-lang/ghc-8.0.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.24.0.0
"
