# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.3

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="CAES Language for Synchronous Hardware - Prelude library"
HOMEPAGE="http://www.clash-lang.org/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+benchmarks doclinks +doctests"

RDEPEND=">=dev-haskell/constraints-0.8:=[profile?] <dev-haskell/constraints-1.0:=[profile?]
	>=dev-haskell/data-binary-ieee754-0.4.4:=[profile?] <dev-haskell/data-binary-ieee754-0.6:=[profile?]
	>=dev-haskell/data-default-0.5.3:=[profile?] <dev-haskell/data-default-0.8:=[profile?]
	>=dev-haskell/ghc-typelits-extra-0.2.1:=[profile?] <dev-haskell/ghc-typelits-extra-0.3:=[profile?]
	>=dev-haskell/ghc-typelits-knownnat-0.2.2:=[profile?] <dev-haskell/ghc-typelits-knownnat-0.3:=[profile?]
	>=dev-haskell/ghc-typelits-natnormalise-0.4.2:=[profile?] <dev-haskell/ghc-typelits-natnormalise-0.6:=[profile?]
	>=dev-haskell/half-0.2.2.3:=[profile?] <dev-haskell/half-1.0:=[profile?]
	>=dev-haskell/lens-4.9:=[profile?] <dev-haskell/lens-4.16:=[profile?]
	>=dev-haskell/quickcheck-2.7:2=[profile?] <dev-haskell/quickcheck-2.11:2=[profile?]
	>=dev-haskell/reflection-2:=[profile?] <dev-haskell/reflection-2.2:=[profile?]
	>=dev-haskell/singletons-1.0:=[profile?] <dev-haskell/singletons-3.0:=[profile?]
	>=dev-haskell/vector-0.11:=[profile?] <dev-haskell/vector-1.0:=[profile?]
	>=dev-lang/ghc-7.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
	test? ( doctests? ( >=dev-haskell/doctest-0.9.1 <dev-haskell/doctest-0.12 ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag benchmarks benchmarks) \
		$(cabal_flag doclinks doclinks) \
		$(cabal_flag doctests doctests)
}
