# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.3

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="CAES Language for Synchronous Hardware - As a Library"
HOMEPAGE="http://www.clash-lang.org/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.6.2.0:=[profile?] <dev-haskell/aeson-1.3:=[profile?]
	>=dev-haskell/attoparsec-0.10.4.0:=[profile?] <dev-haskell/attoparsec-0.14:=[profile?]
	>=dev-haskell/clash-prelude-0.11:=[profile?] <dev-haskell/clash-prelude-0.12:=[profile?]
	>=dev-haskell/concurrent-supply-0.1.7:=[profile?] <dev-haskell/concurrent-supply-0.2:=[profile?]
	>=dev-haskell/data-binary-ieee754-0.4.4:=[profile?] <dev-haskell/data-binary-ieee754-0.6:=[profile?]
	>=dev-haskell/errors-1.4.2:=[profile?] <dev-haskell/errors-2.3:=[profile?]
	>=dev-haskell/fgl-5.4.2.4:=[profile?] <dev-haskell/fgl-5.6:=[profile?]
	>=dev-haskell/hashable-1.2.1.0:=[profile?] <dev-haskell/hashable-1.3:=[profile?]
	>=dev-haskell/lens-3.9.2:=[profile?] <dev-haskell/lens-4.16:=[profile?]
	>=dev-haskell/mtl-2.1.2:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	>=dev-haskell/text-0.11.3.1:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-haskell/unbound-generics-0.1:=[profile?] <dev-haskell/unbound-generics-0.4:=[profile?]
	>=dev-haskell/unordered-containers-0.2.3.3:=[profile?] <dev-haskell/unordered-containers-0.3:=[profile?]
	>=dev-haskell/uu-parsinglib-2.8.1:=[profile?] <dev-haskell/uu-parsinglib-2.10:=[profile?]
	>=dev-haskell/wl-pprint-text-1.1.0.0:=[profile?] <dev-haskell/wl-pprint-text-1.2:=[profile?]
	>=dev-lang/ghc-8.0.1:= <dev-lang/ghc-8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
"
